version: '3'

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list

  build:
    desc: Build the mcp-tester CLI
    sources:
      - cmd/mcp-tester/**/*.go
      - internal/**/*.go
      - go.mod
      - go.sum
    generates:
      - bin/mcp-tester
    cmds:
      - mkdir -p bin
      - GOWORK=off go build -o bin/mcp-tester ./cmd/mcp-tester/

  build-test-server:
    desc: Build the dummy test server
    sources:
      - cmd/test-server/**/*.go
      - internal/**/*.go
      - go.mod
      - go.sum
    generates:
      - bin/test-server
    cmds:
      - mkdir -p bin
      - GOWORK=off go build -o bin/test-server ./cmd/test-server/main.go

  all:
    desc: Build everything
    deps: [build, build-test-server]

  test-list:
    desc: Test the list command
    deps: [all]
    cmds:
      - ./bin/mcp-tester list --command "./bin/test-server"

  test-profile:
    desc: Test the profile functionality
    deps: [all]
    cmds:
      - ./bin/mcp-tester list --profile local

  test-call:
    desc: Test the call command
    deps: [all]
    cmds:
      - ./bin/mcp-tester call echo --command "./bin/test-server" --args '{"message":"Task testing"}'

  test-script:
    desc: Test the script execution
    deps: [all]
    cmds:
      - echo 'call_tool echo "Task script test"' > task_test.mcp
      - ./bin/mcp-tester test --command "./bin/test-server" --script "task_test.mcp"
      - rm task_test.mcp

  test-types:
    desc: Test the type conversion in scripts
    deps: [all]
    cmds:
      - echo 'call_tool add 40 2' > type_test.mcp
      - ./bin/mcp-tester test --command "./bin/test-server" --script "type_test.mcp"
      - rm type_test.mcp

  test-assertions:
    desc: Test the assertion functionality in scripts
    deps: [all]
    cmds:
      - |
        echo 'call_tool add 10 20' > assert_test.mcp
        echo 'assert_contains "Result: 30"' >> assert_test.mcp
      - ./bin/mcp-tester test --command "./bin/test-server" --script "assert_test.mcp"
      - rm assert_test.mcp

  test-vars:
    desc: Test the variable and math assertion functionality
    deps: [all]
    cmds:
      - |
        echo '// Test variables' > vars_test.mcp
        echo 'call_tool add 5 5' >> vars_test.mcp
        echo 'set_var raw_sum structuredContent.a' >> vars_test.mcp
        echo 'assert_number $raw_sum' >> vars_test.mcp
        echo 'call_tool add $raw_sum $raw_sum' >> vars_test.mcp
        echo 'assert_contains "Result: 10"' >> vars_test.mcp
        echo 'assert_gt $raw_sum 4' >> vars_test.mcp
      - ./bin/mcp-tester test --command "./bin/test-server" --script "vars_test.mcp"
      - rm vars_test.mcp

  test-scripts:
    desc: Run the full suite of test scripts
    deps: [all]
    cmds:
      - echo "--- Running Simple Test ---"
      - ./bin/mcp-tester test --profile local --script tests/01_simple.mcp
      - echo "--- Running Types Test ---"
      - ./bin/mcp-tester test --profile local --script tests/02_types_and_equals.mcp
      - echo "--- Running Variables Test ---"
      - ./bin/mcp-tester test --profile local --script tests/03_variables_and_math.mcp
      - echo "--- Running Progress Test ---"
      - ./bin/mcp-tester test --profile local --script tests/05_progress.mcp -v
      - echo "--- Running Cancellation Test ---"
      - ./bin/mcp-tester test --profile local --script tests/06_cancellation.mcp -v

  test-inspect:
    desc: Test the server inspection tool
    deps: [all]
    cmds:
      - ./bin/mcp-tester inspect --profile local

  test-sse:
    desc: Test the SSE transport
    deps: [all]
    cmds:
      - |
        ./bin/test-server -addr :8081 > sse_server.log 2>&1 &
        pid=$!
        echo "Waiting for SSE server to start..."
        sleep 2
        # Use trap to ensure server is killed even if tests fail
        trap "kill $pid" EXIT
        ./bin/mcp-tester inspect --url http://localhost:8081/sse
        ./bin/mcp-tester test --url http://localhost:8081/sse --script tests/01_simple.mcp

  test-all:
    desc: Run all tests
    cmds:
      - task: format
      - task: vet
      - task: staticcheck
      - task: unit-test
      - task: test-list
      - task: test-call
      - task: test-profile
      - task: test-types
      - task: test-assertions
      - task: test-vars
      - task: test-scripts
      - task: test-inspect
      - task: test-sse

  format:
    desc: Format Go source code
    cmds:
      - GOWORK=off go fmt ./...

  vet:
    desc: Examine Go source code and report suspicious constructs
    cmds:
      - GOWORK=off go vet ./...

  staticcheck:
    desc: Advanced static analysis
    cmds:
      - 'GOWORK=off staticcheck ./... || echo "Please install staticcheck: go install honnef.co/go/tools/cmd/staticcheck@latest"'
    ignore_error: true

  complexity:
    desc: Check cognitive complexity
    cmds:
      - 'GOWORK=off gocognit -over 15 . || echo "Please install gocognit: go install github.com/uudashr/gocognit/cmd/gocognit@latest"'
    ignore_error: true

  test-coverage:
    desc: Run tests with coverage report
    cmds:
      - GOWORK=off go test -coverprofile=coverage.out ./...
      - GOWORK=off go tool cover -func=coverage.out
      - GOWORK=off go tool cover -html=coverage.out -o coverage.html

  unit-test:
    desc: Run internal unit tests
    cmds:
      - GOWORK=off go test -v ./internal/... ./cmd/mcp-tester/...


  release-test:
    desc: Test the release process locally
    cmds:
      - goreleaser release --snapshot --clean

  clean:
    desc: Remove binaries and temporary files
    cmds:
      - rm -rf bin task_test.mcp type_test.mcp assert_test.mcp *.png sse_server.log
